### PR TITLE
RecurrentUNet Initial Implementation

### PR DESCRIPTION
**Pull request by boykovdn**
I welcome any suggestions for improvement!

* forward() still a work in progress
* Should the forward() function work on (batch, channel, x, y) or (batch, channel, t, x, y)? The latter would more explicitly point the user that the network is meant to work on sequential data.
* Note: Is batching supposed to somehow work with the ConvGRUs? The way I see it, each member of a sequence has to be .forward-ed individually through the recurrent modules, which means we cannot use batches. Or am I wrong?

### CODE REVIEW

**Comment by boykovdn** [comment]
(haven't tested the actual code yet, so there are bugs)

**Comment by imagirom** [comment]
Looks good!

> * Should the forward() function work on (batch, channel, x, y) or (batch, channel, t, x, y)? The latter would more explicitly point the user that the network is meant to work on sequential data.

I would have said (batch, channel, t, x, y), but your current solution with the `sequence` parameter allowing to specify this also seems fine to me.

> * Note: Is batching supposed to somehow work with the ConvGRUs? The way I see it, each member of a sequence has to be .forward-ed individually through the recurrent modules, which means we cannot use batches. Or am I wrong?

I do not know. I think batching would complicate things, at least if the sequence lengths differ.

I would say you work with and debug your code for a bit, then you can just go ahead and merge this. Oh, and maybe delete the broken and therefore commented out `RecurrentUNet2d` below your implementation.

**Comment by boykovdn** [comment]
Copied from #3 before closing (changes integrated into this PR)

* Main change is that ConvGRUCell no longer needs to be passed the previous state. This is needed because in order to build a Recurrent Unet that subclasses UNet, the previous state would have to be saved and propagated up through all the forward calls. It is, I think, also more natural to have the hidden state saved inside each cell.

* Remove depreciation warning from using functional.sigmoid, functional.tanh by switching to torch.sigmoid, torch.tanh.

* Add padding to GRU convolution, which was missing and causing problems (e.g. conv kernel being bigger than input)

**Comment by boykovdn** [comment]
Produces the results I expect, so will merge it.

**Pull request merged**
